export const theme = Object.freeze({
  colors: Object.freeze({
    canvas: '#f4f7fb',
    surface: '#ffffff',
    surfaceMuted: '#f7fafc',
    textPrimary: '#071333',
    textSecondary: '#506695',
    textMuted: '#7182a6',
    border: '#dce4ee',
    grid: '#dfe7f0',
    accent: '#0bb3a7',
    accentStrong: '#008e7f',
    accentSoft: '#e2f7f4',
    accentArea: '#dff6f3',
    secondary: '#3569d4',
    secondarySoft: '#e9effc',
    success: '#08b45b',
    successSoft: '#e8f8ef',
    warning: '#c66a08',
    warningSoft: '#fff2dc',
    danger: '#ff2028',
    dangerSoft: '#ffeaeb',
    dangerArea: '#fff0f1',
    white: '#ffffff',
    focus: '#276ef1',
    tooltipShadow: 'rgba(15, 33, 68, 0.18)',
    cardShadow: 'rgba(22, 42, 79, 0.08)',
    chartShadow: 'rgba(11, 179, 167, 0.24)',
  }),
  typography: Object.freeze({
    family: 'Inter, ui-sans-serif, system-ui, -apple-system, sans-serif',
  }),
  radius: Object.freeze({
    small: '0.625rem',
    medium: '0.875rem',
    large: '1.125rem',
    pill: '999px',
  }),
  shadow: Object.freeze({
    card: '0 0.5rem 1.5rem var(--color-card-shadow)',
    tooltip: '0 0.75rem 2rem var(--color-tooltip-shadow)',
  }),
})

const cssVariables = Object.freeze({
  '--color-canvas': theme.colors.canvas,
  '--color-surface': theme.colors.surface,
  '--color-surface-muted': theme.colors.surfaceMuted,
  '--color-text-primary': theme.colors.textPrimary,
  '--color-text-secondary': theme.colors.textSecondary,
  '--color-text-muted': theme.colors.textMuted,
  '--color-border': theme.colors.border,
  '--color-grid': theme.colors.grid,
  '--color-accent': theme.colors.accent,
  '--color-accent-strong': theme.colors.accentStrong,
  '--color-accent-soft': theme.colors.accentSoft,
  '--color-accent-area': theme.colors.accentArea,
  '--color-secondary': theme.colors.secondary,
  '--color-secondary-soft': theme.colors.secondarySoft,
  '--color-success': theme.colors.success,
  '--color-success-soft': theme.colors.successSoft,
  '--color-warning': theme.colors.warning,
  '--color-warning-soft': theme.colors.warningSoft,
  '--color-danger': theme.colors.danger,
  '--color-danger-soft': theme.colors.dangerSoft,
  '--color-danger-area': theme.colors.dangerArea,
  '--color-white': theme.colors.white,
  '--color-focus': theme.colors.focus,
  '--color-tooltip-shadow': theme.colors.tooltipShadow,
  '--color-card-shadow': theme.colors.cardShadow,
  '--color-chart-shadow': theme.colors.chartShadow,
  '--font-family': theme.typography.family,
  '--radius-small': theme.radius.small,
  '--radius-medium': theme.radius.medium,
  '--radius-large': theme.radius.large,
  '--radius-pill': theme.radius.pill,
  '--shadow-card': theme.shadow.card,
  '--shadow-tooltip': theme.shadow.tooltip,
})

export function applyTheme(root = document.documentElement) {
  for (const [property, value] of Object.entries(cssVariables)) {
    root.style.setProperty(property, value)
  }
}
